### ISSUE TITLE
关于模型的应用

### ISSUE THREAD

**Issue by YEA02** [loginaway/Metapath2vec#1]
你好，我运行这个模型出了点问题

**Comment by YEA02** [comment]
![image](https://user-images.githubusercontent.com/41103143/70861554-7b121b00-1f6a-11ea-9884-18bb407c7492.png)
装完requirement之后执行python metapath2vec.py -file walks.txt -embed_dim 64 -epoch 10 -types ac -outname embeddings，执行结果截图🤣

**Comment by loginaway** [comment]
你好，这只是一个示例文件，用来指引你构建自己的训练序列。可以参考一下README.md里面的内容。

**Comment by YEA02** [comment]
嗯嗯，我是照着README里面的步骤执行的。
替换dataset之后，还需要调整别的地方吗？
demo的执行结果是这样的，是因为没有调参吗？ 
谢谢！

**Comment by loginaway** [comment]
替换dataset之后，还需要根据你dataset中序列的节点种类设置-types选项，比如walks.txt中只有a和c两种节点，就设置-types ac。
demo的执行结果看上去没问题呀，因为我原来只在walks.txt里面放了四段序列，自然一个epoch只有4/4吧😂。至于loss，我可能没有做归一化，当时只是为了判断loss是否下降而已。欢迎修改后pull request。

**Comment by YEA02** [comment]
嗷，这样呀  那可能是因为数据集小了吧 ，执行了一分钟都不到就结束了hhhh  
我是菜鸡不会改代码🤣 🤣
感谢解答！！
